# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Keynote' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod "PromiseKit"
  pod 'RxSwift'
  pod 'RxCocoa'

  # Pods for Keynote

  target 'KeynoteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KeynoteUITests' do
    # Pods for testing
  end

end
